spring:
    datasource:
        url: jdbc:mysql://localhost:3306/youran?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
logging:
    level:
        root: info
        java:
            sql: debug
        com:
            youran: trace
swagger:
    enabled: true
youran:
    data-dir: D:\\youran
    default-user-init: true
    security-enabled: false
