spring:
    datasource:
        url: jdbc:mysql://localhost:3306/youran?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: root
#youran:
#    generate:
#        devMode: 1
#        devProjectDir: D:\\workspace_cbb\\youran-sample
