server:
    context-path: /
    port: 8080
spring:
    application:
        name: youran-generate
    profiles:
        active: local
    # 强制指定响应头content-type是utf-8编码
    http:
        encoding:
            force: true

swagger:
    basePackage: com.youran.generate

mybatis:
    config-location: classpath:mybatis-config.xml

youran:
    generate:
        aesKey: orpNB6YGbiiDcrrubk2rFQ==
        version: 20
        rootPath: generate
