spring:
    datasource:
        url: jdbc:mysql://localhost:3306/youran?master=1&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=GMT&serverTimezone=Asia/Shanghai
        username: root
        password: root
logging:
    level:
        root: info
        java:
            sql: debug
        com:
            youran: trace
swagger:
    enabled: true
youran:
    devMode: 1
    dev-project-dir: D:\\workspace_cbb\\auto
    security-enabled: false
