server:
    servlet:
        context-path: /
    port: 8080
spring:
    application:
        name: youran-generate
    profiles:
        active: local
    # 强制指定响应头content-type是utf-8编码
    http:
        encoding:
            force: true
    security:
        user:
            name: root
            password: root
    servlet:
        multipart:
            max-request-size: 100MB
            max-file-size: 100MB
swagger:
    base-package: com.youran.generate

mybatis:
    config-location: classpath:mybatis-config.xml

youran:
    aesKey: orpNB6YGbiiDcrrubk2rFQ==
    version: 3.0.0
    apiPath: /api
    wsApiPath: /ws_api
    security-enabled: true

