server:
    context-path: /
    port: 8080
spring:
    application:
        name: youran-sample
    profiles:
        active: local
    http:
        encoding:
            force: true

swagger:
    basePackage: com.cbb.sample

mybatis:
    config-location: classpath:mybatis-config.xml

com:
    cbb:
        sample:
            rootPath: sample
